### ISSUE TITLE
Buffering /dev/urandom ?

### ISSUE THREAD

**Issue by mrclay** [GeorgeArgyros/Secure-random-bytes-in-PHP#7]
functions like [drupal_random_bytes](http://api.drupal.org/api/drupal/core%21includes%21bootstrap.inc/function/drupal_random_bytes/8) go ahead and request the full 4096 bytes from /dev/urandom and buffer the unreturned bytes in a static var. Have you considered this?

**Comment by GeorgeArgyros** [comment]
Yes, but usually you would like to use this function to get a few strong random bytes and then feed them into a faster PRNG as seed. By default PHP when reading a file fills a buffer similarly to what you propose, however in the case of /dev/urandom this hurts performance since we usually request far less than 4096 bytes. Therefore, we even disable the buffering done by the runtime (@stream_set_read_buffer($handle, 0)).
